spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource #默认的连接池
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123

#    自动建表和插入数据，以下是选择ddl和dml的默认选项
    schema-username: root
    schema-password: 123
    schema:
      - classpath:schema.sql
    data-username: root
    data-password: 123
    data:
      - classpath:data.sql
    #    initialization-mode: always会自动顺序读取classpath:下schema.sql和data.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

